name: Deploy to GitHub Pages (classic)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.21'

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build with repo base
        env:
          VITE_BASE: "/${{ github.event.repository.name }}/"
        run: |
          bun run build
          bun run postbuild  # copies index.html -> 404.html and adds .nojekyll
          # quick debug
          ls -la dist
          sed -n '1,120p' dist/index.html | sed -n '1,40p'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true